### ISSUE TITLE
Translation snapping

### ISSUE THREAD

**Issue by babooncodes** [MrUnit64/RotationAnarchy#12]
(tile width scale e.g. 0.25 tile wide, 0.5 tile wide and 1 tile wide). Example, you put a wall down at a weird angle, and using snap translation you can quickly and seemlessly build a five tile wide wall. You wouldn't need to work out what grid to work on etc and it would make building a building that's off grid so quick and easy.

**Comment by Distantz** [comment]
Done in new release.
